### ISSUE TITLE
MemoEncoder.findMemo is Very Slow

### ISSUE THREAD

**Issue by blackandwhitebg** [henck/dBASE.NET#3]
Hi,

I was able to improve the time to read a big DBF file (about 200MB) with a FPT (which is about 2MB), and the result was not even comparable - **Dbf.Read was taking 10 minutes, and is now taking 4 seconds**. Apparently - the LINQ methods are super inefficient.

The implementation I suggest is:

```
private static string findMemo(int index, byte[] memoData)
{
	// The index is measured from the start of the file, even though the memo file header blocks takes
	// up the first few index positions.

	UInt16 blockSize = BitConverter.ToUInt16(new[] { memoData[7], memoData[6] }, 0);
	int length = (int)BitConverter.ToUInt32(new[]
		{
			memoData[index * blockSize + 4 + 3],
			memoData[index * blockSize + 4 + 2],
			memoData[index * blockSize + 4 + 1],
			memoData[index * blockSize + 4 + 0],
		}, 0);

	byte[] memoBytes = new byte[length];
	int lengthToSkip = index * blockSize + 8;

	for (int i = lengthToSkip; i < lengthToSkip + length; ++i)
	{
		memoBytes[i - lengthToSkip] = memoData[i];
	}
			
	string text = Encoding.ASCII.GetString(memoBytes).Trim();
	return text;
}
```

Thank you!
Chris

**Comment by henck** [comment]
This is what I love about open source development. I had not had a use case with a 200MB DBF before, so I didn't have any data about decoding speed. Thank you for finding this, and for submitting this code. I have committed it.

It is interesting to see that these LINQ methods are orders of magnitude slower than simple array indexing. You might expect them to be slightly slower due to overhead and a generic approach, but this much? Anyway, much better now.

I think there are other uses of LINQ methods in the source. I'll have to go through it to root them out.
